### ISSUE TITLE
Listener -> Insert to DB

### ISSUE THREAD

**Issue by daisymariebernante** [parkerjettt/TJPubslack#2]
Listener means Pub/Sub, 

Si Pub/Sub mo listen for any publishing then siyay mo insert to Db.

For example. 

Nay mo send JSON Format of data. si Pub/Sub mo dawat then mo send to database. which is Spanner

Feel free to use files inside sa Current Progress E open lng ng current progress, pislita ng repository named TJPubSubSlack

**Comment by parkerjettt** [comment]
Lague, Bernante, Acson

Done updating.
